GSUB lookup table type 7 subtable format 1
opentypejs/opentype.js pull request #486
Opened 2021-08-12 01:53 UTC by st0nerhat

## Description

_In featureQuery.js:chainingSubstitutionFormat3_
- Modify var types of subtable, lookup, and substitutionType to be lets so they can be mutated in the next step.
- Detect substitution type "71" which means lookup table type 7 and format 1. 
- When detected, mutate the substitution type and lookup method based on the linked extension subtable
- Finally update the subtable variable to be the extension table
- Throw an error if the chained substitution type is not handled. This will avoid fonts that use chaining substitutions from silently rendering incorrectly if they use an unhandled changed substitution.

_In featureQuery.js:FeatureQuery.prototype.lookupFeature_

Same changes as above.

## Motivation and Context

Addresses issue #415 

GSUB tables have a lookup table type 7 called the Extension Substitution Subtable. Only one format officially exists (format 1). 
See the [OpenType spec page](https://docs.microsoft.com/en-us/typography/opentype/spec/gsub#lookuptype-7-extension-substitution).

Per the spec, Extension tables are used in fonts that use a large number of substitution subtables. Fonts for scripts where letters are connected are a situation where many substitutions are needed.

## How Has This Been Tested?

So far I have tested this on 3 custom fonts in my library, one of which contains type 7 lookup tables and 2 that do not. Unfortunately I do not have the license to upload these fonts in the PR.

## Screenshots (if appropriate):

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [X] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [X] I did `npm run test` and all tests passed green (including code styling checks).
- [x] I have added tests to cover my changes.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the **README** accordingly.
- [X] I have read the **CONTRIBUTING** document.

2022-01-14 22:34 UTC, Connum commented
> Unfortunately I do not have the license to upload these fonts in the PR.
The tests don't use actual font files to run (see https://github.com/opentypejs/opentype.js/pull/454/commits/3177c13446f79542cc11b5958b5083f6cbce5e48 for example), so it would be great if you could add (a) test case(s) to your contribution!

2023-02-02 20:42 UTC, ILOVEPIE commented
@st0nerhat please rebase onto and create a pull request for the new active development fork [here](https://github.com/SABRE-JS/opentype.js)

2023-02-02 22:22 UTC, Connum requested changes
requires test(s)

2023-02-11 22:30 UTC, Connum commented
I just added a PR FilamentGames#2 to the feature branch that adds a test for this parsing feature. @st0nerhat, could you please merge that so we can get this PR merged?

2023-02-13 16:10 UTC, Connum approved these changes

2023-02-13 16:12 UTC, Connum commented
As I provided the test, a different reviewer should make a review as well, so I tagged @ILOVEPIE

2023-02-13 22:09 UTC, ILOVEPIE approved these changes
Looks good to me, apart from the fact that we're still uncertain on the tests/no examples in the microsoft documentation, perhaps we should check how libfreetype handles it?

2023-02-15 23:12 UTC, Connum commented
> Looks good to me, apart from the fact that we're still uncertain on the tests/no examples in the microsoft documentation, perhaps we should check how libfreetype handles it?

The functionality is relatively straight-forward. I tried looking at libfreetype, but I didn't know where to look exactly. In my opinion, the test that we have now should be sufficient.

2023-02-26 21:20 UTC, Connum commented
I haven't come across a better stripped down example for a test, but I didn't come across any problems either so far, so I'm merging this now.

2023-02-26 21:21 UTC, merged