fix reading-writing.thml
opentypejs/opentype.js pull request #593
Opened 2023-04-16 08:45 UTC by moontypespace

## Description
Fixed some path to missing font.
Fixed font name.
Replaced opentype.js directory path with CDN link.

## Motivation and Context
The example page reading-wrting.html did not work anymore.

## How Has This Been Tested?
Created a localhost server and tested in chrome.
The characters are display correct now.
Download a font work again.

## Screenshots (if appropriate):
<img width="1837" alt="Screenshot 2023-04-16 at 10 39 29" src="https://user-images.githubusercontent.com/21055547/232287106-9dc7b912-96f8-457b-aef3-4023fd711655.png">

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [ ] I did `npm run test` and all tests passed green (including code styling checks).
- [ ] I have added tests to cover my changes.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the **README** accordingly.
- [x] I have read the **CONTRIBUTING** document.

2023-04-16 11:27 UTC, Connum commented
Thanks! Doesn't look like a breaking change though, as it only fixes an example file

2023-04-16 16:33 UTC, moontypespace commented
> Thanks! Doesn't look like a breaking change though, as it only fixes an example file

Sure, but it broke the HTML ;)

2023-05-19 00:58 UTC, yne commented on docs/examples/reading-writing.html
is the full https URL really required ? others pages don't seems to need it

2023-05-19 00:59 UTC, yne requested changes
beside the URL remake, this PR looks nice

2023-10-27 14:14 UTC, Connum commented
This was already fixed via d9e369e8b0e9d081dc1d752cfca89967d0bae8d8 in the master.

2023-10-27 14:14 UTC, closed without merging